const $=id=>document.getElementById(id);
let client=null,sessionId=null,myUserId=null,leftCount=0;
const people=new Map(),offTimers=new Map();
const key=()=>$('key').value.trim();
const headers=()=>({'content-type':'application/json','x-monitor-key':key()});
const api=async(url,opt={})=>{const r=await fetch(url,{...opt,headers:{...headers(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function note(t,ok=true){$('msg').textContent=t;$('msg').className=ok?'ok':'err'}
function badge(t,live=false){$('status').textContent=t;$('status').className=live?'badge live':'badge'}
function normalize(u){return{id:String(u.userId??u.userID??u.id??''),name:u.displayName||u.userName||u.screenName||'Noma’lum',video:!!(u.bVideoOn??u.videoOn??u.isVideoOn),phone:!!(u.isPhoneUser||Number(u.userType)===5)}}
async function log(type,p,message=''){if(!sessionId||!p)return;await api('/api/event',{method:'POST',body:JSON.stringify({sessionId,type,userId:p.id,name:p.name,phone:p.phone,video:p.video,message})}).catch(()=>{});const line=document.createElement('div');line.className='event';line.innerHTML=`<b>${new Date().toLocaleTimeString('uz-UZ')} — ${p.name}</b><span>${message||type}</span>`;$('events').prepend(line)}
function setPerson(p,isNew=false){if(!p.id||p.id===myUserId)return;const old=people.get(p.id);people.set(p.id,{...old,...p});if(isNew&&!old)log('joined',p,`Zoomga kirdi. Kamera: ${p.video?'yoqilgan':'o‘chirilgan'}`);if(!p.video&&!offTimers.has(p.id)){offTimers.set(p.id,Date.now());if(old&&old.video)log('camera_off',p,'Kamera o‘chirildi')}if(p.video&&offTimers.has(p.id)){const ms=Date.now()-offTimers.get(p.id);offTimers.delete(p.id);if(old&&!old.video)log('camera_on',p,`Kamera yoqildi. OFF vaqt: ${(ms/60000).toFixed(1)} daq`)}render()}
function removePerson(raw){const p=normalize(raw),old=people.get(p.id);if(!old||p.id===myUserId)return;leftCount++;log('left',old,'Zoomdan chiqdi');people.delete(p.id);offTimers.delete(p.id);render()}
function render(){let on=0,off=0,phone=0;const rows=[];for(const p of people.values()){if(p.video)on++;else off++;if(p.phone)phone++;const ms=p.video?0:(offTimers.has(p.id)?Date.now()-offTimers.get(p.id):0);rows.push(`<tr><td><b>${p.name}</b></td><td><span class="pill ${p.video?'on':'off'}">${p.video?'YOQILGAN':'O‘CHIQ'}</span></td><td>${p.video?'—':(ms/60000).toFixed(1)+' daq'}</td><td>${p.phone?'📞 Phone/PSTN':'Zoom client'}</td></tr>`)}$('people').innerHTML=rows.join('')||'<tr><td colspan="4">Qatnashchi yo‘q</td></tr>';$('sOnline').textContent=people.size;$('sOn').textContent=on;$('sOff').textContent=off;$('sPhone').textContent=phone;$('sLeft').textContent=leftCount}
async function authStatus(){if(!key()){$('authState').value='MONITOR_KEY kiriting';return false}try{const d=await api('/api/oauth/status');$('authState').value=d.authorized?'Avtorizatsiya qilingan':'Avtorizatsiya qilinmagan';return !!d.authorized}catch(e){$('authState').value='Tekshirib bo‘lmadi';return false}}
async function zoomAuth(){try{if(!key())throw new Error('MONITOR_KEY kiriting');const meeting=$('meeting').value.replace(/\D/g,'');const d=await api('/api/oauth/start',{method:'POST',body:JSON.stringify({meetingNumber:meeting})});location.href=d.authorizationUrl}catch(e){note(e.message,false)}}
async function changeZoomAccount(){try{if(!key())throw new Error('MONITOR_KEY kiriting');await api('/api/oauth/logout',{method:'POST',body:'{}'}).catch(()=>{});$('authState').value='Avtorizatsiya qilinmagan';note('Zoom akkaunt uzildi. Yangi akkaunt bilan avtorizatsiya qiling.');await sleep(250);zoomAuth()}catch(e){note(e.message,false)}}
async function getObfWithRetry(meeting,waitSeconds=120){let lastErr='';const deadline=Date.now()+waitSeconds*1000;while(Date.now()<deadline){try{return (await api('/api/obf',{method:'POST',body:JSON.stringify({meetingNumber:meeting})})).obfToken}catch(e){lastErr=e.message||String(e);note('Boshqa kishi ochgan meeting: avtorizatsiya qilingan Zoom akkaunt meetingga kirishini kutyapman...');await sleep(3000)}}throw new Error(`${lastErr||'OBF token olinmadi'}. Avtorizatsiya qilingan Zoom akkaunt shu meeting ichida bo‘lishi kerak.`)}
function friendlyJoinError(e,external){const raw=String(e?.reason||e?.message||e||'Zoom join xatosi');if(/4011|publish|marketplace|review/i.test(raw))return 'Tashqi meetingga kirish Zoom Marketplace review/publish tasdig‘ini talab qilmoqda. App tasdiqlangach shu rejim ishlaydi.';if(/4017|authorized user not in meeting|not in meeting/i.test(raw))return 'Avtorizatsiya qilingan Zoom akkaunt meeting ichida aniqlanmadi. O‘sha akkaunt bilan meetingga kiring va qayta urinib ko‘ring.';if(external&&/obf|on behalf/i.test(raw))return `OBF avtorizatsiya xatosi: ${raw}`;return raw}
async function start(){let external=false;try{if(!key())throw new Error('MONITOR_KEY kiriting');const meeting=$('meeting').value.replace(/\D/g,'');if(!meeting)throw new Error('Meeting ID kiriting');external=$('meetingMode')?.value!=='same';badge('Ulanmoqda');let obfToken='';if(external){const authorized=await authStatus();if(!authorized)throw new Error('Boshqa kishi ochgan meeting uchun avval Zoom bilan avtorizatsiya qiling');note('OBF token tayyorlanmoqda...');obfToken=await getObfWithRetry(meeting,120)}
const sig=await api('/api/signature',{method:'POST',body:JSON.stringify({meetingNumber:meeting,role:0})});const ses=await api('/api/session/start',{method:'POST',body:JSON.stringify({meetingNumber:meeting})});sessionId=ses.id;$('report').href=`/api/session/${sessionId}/report.xlsx?key=${encodeURIComponent(key())}`;$('report').classList.remove('disabled');if(!window.ZoomMtgEmbedded)throw new Error('Zoom SDK yuklanmadi');client=ZoomMtgEmbedded.createClient();await client.init({zoomAppRoot:$('meetingSDKElement'),language:'en-US',patchJsMedia:true,leaveOnPageUnload:true});client.on('user-added',payload=>{for(const u of(payload||[]))setPerson(normalize(u),true)});client.on('user-removed',payload=>{for(const u of(payload||[]))removePerson(u)});client.on('user-updated',payload=>{for(const u of(payload||[]))setPerson(normalize(u),false)});await client.join({signature:sig.signature,meetingNumber:meeting,password:$('pass').value||'',userName:$('name').value||'Buxoro Zoom Monitor',...(obfToken?{obfToken}:{})});const list=client.getAttendeeslist?.()||[];const me=client.getCurrentUser?.();if(me)myUserId=String(me.userId??me.userID??'');for(const u of list)setPerson(normalize(u),true);$('start').disabled=true;$('stop').disabled=false;badge('LIVE',true);note(`Monitoring boshlandi${external?' — boshqa host meetingi OBF orqali':''}.`)}catch(e){console.error('Zoom join error',e);badge('Xatolik');note(friendlyJoinError(e,external),false)}}
async function stop(){try{if(sessionId)await api(`/api/session/${sessionId}/stop`,{method:'POST',body:'{}'}).catch(()=>{});await client?.leaveMeeting?.();client=null;$('start').disabled=false;$('stop').disabled=true;badge('To‘xtatildi');note('Monitoring to‘xtatildi. Excel hisobot tayyor.')}catch(e){note(e.message,false)}}
$('zoomAuth').onclick=zoomAuth;$('changeZoom').onclick=changeZoomAccount;$('start').onclick=start;$('stop').onclick=stop;$('health').onclick=async()=>{try{const d=await api('/api/health');await authStatus();note(`Server OK. Zoom: ${d.zoomConfigured?'tayyor':'yo‘q'}, Telegram bot: ${d.telegramConfigured?'tayyor':'yo‘q'}`)}catch(e){note(e.message,false)}};
const qs=new URLSearchParams(location.search);if(qs.get('zoom_auth')==='ok'){note('Zoom avtorizatsiyasi muvaffaqiyatli. Boshqa kishi host bo‘lsa ham mumkin: avtorizatsiya qilingan akkaunt bilan o‘sha meetingga oddiy qatnashchi sifatida kiring, keyin monitoringni boshlang.');if(qs.get('meeting'))$('meeting').value=qs.get('meeting');history.replaceState({},'',location.pathname)}
setInterval(()=>{render();const lim=Number($('limit').value||0);if(!lim)return;for(const[id,t]of offTimers){const p=people.get(id);if(p&&!p.warned&&Date.now()-t>=lim*60000){p.warned=true;log('camera_off_long',p,`Kamera ${lim}+ daqiqa o‘chiq`)}}},1000);
